"""add_error_message_to_document

Revision ID: 1afffee6feaa
Revises: 0269f0db9f4c
Create Date: 2026-04-26 10:13:07.905798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1afffee6feaa'
down_revision: Union[str, None] = '0269f0db9f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_deals_document_id'), 'deals', ['document_id'], unique=False)
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_message')
    op.drop_index(op.f('ix_deals_document_id'), table_name='deals')
    # ### end Alembic commands ###
